apiVersion: automation.cio/v1alpha1
kind: RepositoryConfig
ealImapNumber: EAL-010456
build:
  strategy: cirrus-deployment
  pipeline: java-v11-mvn-ol-container-image  
  version: v2
  config:
    cirrus-project-name: cio-coaches-india
    cirrus-pipeline-name: cicd-java
    cirrus-pipeline-username: "encrypted:v1:AAABgU1neI75QIbk9f+sZNgReGU9BavN3CqaRE1A0I2IGGTdE0aRgES9iAflCTjLlkkJahlbqLQOAuXwxUdIICh1SSUk/9WZEQBl02O7748L6B1NE2i95uGopPKEpePlAVdp7N39up2epVr2Z6F5P6lxBZyeACowOPfwX8n+72BufMZl3cxJcaqjsOKChl51"
    cirrus-pipeline-password: "encrypted:v1:AAABgU1neI4+yWUsZLSBe9YDMDeAue+hPAWw16lls5ctfuX8U0ZBz1a063K6r9hsMNsr5OaPdU3yGIYfidTyj81fM3uBxckXKsxzZiZsNs9S1P0ajdWwBfp610X235/XHbqCm/kVRcsr6DXwevjkQlpo8a3mRmoGxQzj1eRlZ5zLj/S2YEIeDFuU7QwASwCqpjryaTVtE+9mcnzUrcijBzJHawtZMs2G"
    cirrus-region: us-south1    
    cirrus-api-username: "encrypted:v1:AAABgU1neI4HoGrf+Icc16NKMfaigVIRK7KAXZUeIZKkoj4a6FZ1N6uPqQKOIg3VtkGCAGlR+ssXo5/fNS+mZ1TYTaBWEhA7NdCkcqoYbLOJqECdoGQLzqMT+F9Ish6z1XR0dG7j8Bj4hY9sAawu2oT3/eCejquaiSR3+xUA3ybsNU/XWjtsylHfmEy207eojqTx"
    cirrus-api-password: "encrypted:v1:AAABgU1neI4YkOCBQ7asRbv1XSUcdhxT0oU6eVoEXCG/0YBJMqcXn7J3FZEfIWq4mnnzPWydBH+Nk0wm+LGbx+jJh2FGvViixTzN/2puVVt7nGmr08gxIl+t2krUkqhcRQ2OwmWw4/R5eF4jwJX/xlLyDlGhkCeORAYG/4c43VTlSBwqf/MCKMpg/LTdXYEth9P2Z8rc1EKL1vO0Nvxlwf+tQdHapLOiZgg9ZgpUTQ=="
    